apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: argocd-teste-config-location
  description: Location to import all argocd-teste-config catalog components
spec:
  targets:
    - ./.platform/*.yaml
