apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "argocd-teste-config"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: staging
    grafana_obs_api: https://grafana.cluster-angelica-apr.vkpr.platform.vee.codes
    public_ip: 34.200.112.30
  annotations:
    github.com/project-slug: veecode-homolog/argocd-teste-config
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$34.200.112.30 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$34.200.112.30:~/.kube/config ~/.kube/config-argocd-teste-config\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"34.200.112.30\")' -i ~/.kube/config-argocd-teste-config\n  export KUBECONFIG=~/.kube/config-argocd-teste-config\n  kubectl get pods -A\n"
    veecode/cluster-name: argocd-teste-config
    kubernetes.io/secret-name: argocd-teste-config-secret
    kubernetes.io/secret-namespace: veecode-homolog
    kubernetes.io/auth-provider: custom
    kubernetes.io/api-server: https://34.200.112.30:6550
    kubernetes.io/skip-tls-verify: "true"
    kubernetes.io/skip-metrics-lookup: "false"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
